package com.drools.example

import java.io.FileInputStream

import org.kie.api.runtime.KieRuntime

import javafx.scene.control.Alert
import javafx.scene.control.ButtonType
import javafx.scene.image.Image
import javafx.scene.image.ImageView
import javafx.scene.control.DialogPane
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.StackPane
import javafx.scene.control.Label
import javafx.scene.layout.GridPane
import javafx.geometry.Pos
import javafx.scene.text.Font
import javafx.stage.Stage
import javafx.scene.control.Button
import javafx.scene.Scene


declare QuestionAnswer
    ans : String
end


declare AlbumAnswer
    album : Album
    ans   : String
end


global Stage primaryStage

rule "Initial rule"
when

then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.KANYE_WEST_808S_HEARTBREAK);
    insert( albumAnswer );

end

rule "Album Answer yes"
when
    a  : AlbumAnswer( ans.equals("Yes") )
then

	FileInputStream albumPath = new FileInputStream(a.getAlbum().getPathName());
    Image img = new Image(albumPath);
    ImageView imageV = new ImageView(img);
	
	
    Alert alerts = new Alert(Alert.AlertType.NONE, "", ButtonType.CLOSE );
	DialogPane dialogPane = alerts.getDialogPane();
    GridPane grid = new GridPane();
    
    Label topLabel = new Label("Your choice:");
    topLabel.setAlignment(Pos.CENTER);
    topLabel.setMaxWidth(Double.MAX_VALUE);
    topLabel.setMaxHeight(Double.MAX_VALUE);
    topLabel.setMinHeight(80.0);
    topLabel.setFont(new Font("Arial", 20));
    grid.add(topLabel, 0,0);
    
    StackPane stackPane = new StackPane(imageV);
    stackPane.setMinWidth(400);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,1);

    Label bottomLabel = new Label(a.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,2);

    dialogPane.setHeader(grid);
    alerts.showAndWait();
     
end

rule "Kanye West - 808 & Heartbreak no answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.KANYE_WEST_808S_HEARTBREAK )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                    "Come on, I want REAL rap music", "Give me some nice hip-hop beats");

    insert( questionAnswer );

end

rule "Come On, I want REAL rap music"
when
    questionAnswer : QuestionAnswer( ans.equals("Come on, I want REAL rap music") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.GIRL_TALK_FEED_THE_ANIMALS);
    insert( albumAnswer );

end




declare enum Album
   APHEX_TWIN_DRUKQS("Aphex Twin - Drukqs", "src/main/resources/images/Aphex Twin - Drukqs.jpg"),
   APHEX_TWIN_SELECTED_AMBIENT_WORKS("Aphex Twin - Selected Ambient Works", "src/main/resources/images/Aphex Twin - Selected Ambient Works.jpg"),
   AUTECHRE_AMBER("Autechre - Amber", "src/main/resources/images/Autechre - Amber.jpg"),
   BOARDS_OF_CANADA_MUSIC_HAS_THE_RIGHT_TO_CHILDREN("Boards of Canada - Music Has the Right to Children", "src/main/resources/images/Boards of Canada - Music Has the Right to Children.jpg"),
   BONOBO_BLACK_SANDS("Bonobo - Black Sands", "src/main/resources/images/Bonobo - Black Sands.jpg"),
   BRIAN_ENO_AMBIENT_1_MUSIC_FOR_AIRPORTS("Brian Eno - Ambient 1 Music For Airports", "src/main/resources/images/Brian Eno - Ambient 1 Music For Airports.jpg"),
   BRIAN_ENO_AMBIENT_2_PLATEAUX_OF_MIRROR("Brian Eno - Ambient 2 Plateaux Of Mirror", "src/main/resources/images/Brian Eno - Ambient 2 Plateaux Of Mirror.jpg"),
   BURIAL_UNTRUE("Burial - Untrue", "src/main/resources/images/Burial - Untrue.jpg"),
   DJ_SHADOW_ENDTRODUCING("DJ Shadow - Endtroducing", "src/main/resources/images/DJ Shadow - Endtroducing......jpg"),
   DAFT_PUNK_DISCOVERY("Daft Punk - Discovery", "src/main/resources/images/Daft Punk - Discovery.jpg"),
   DARKSIDE_PSYCHIC("Darkside - Psychic", "src/main/resources/images/Darkside - Psychic.jpg"),
   FUCK_BUTTONS_TAROT_SPORT("Fuck Buttons - Tarot Sport", "src/main/resources/images/Fuck Buttons - Tarot Sport.jpg"),
   GIRL_TALK_FEED_THE_ANIMALS("Girl Talk - Feed The Animals", "src/main/resources/images/Girl Talk - Feed The Animals.jpg"),
   GLOBAL_COMMUNICATION_76_14("Global Communication - 76 14", "src/main/resources/images/Global Communication - 76 14.jpg"),
   GODSPEED_YOU_BLACK_EMPEROR_LIFT_YOUR_SKINNY_FISTS_LIKE_ANTENNAS_TO_HEAVEN("Godspeed You! Black Emperor - Lift Your Skinny Fists Like Antennas to Heaven", "src/main/resources/images/Godspeed You! Black Emperor - Lift Your Skinny Fists Like Antennas to Heaven.jpg"),
   GOLDIE_TIMELESS("Goldie - Timeless", "src/main/resources/images/Goldie - Timeless.jpg"),
   HELIOS_EINGYA("Helios - Eingya", "src/main/resources/images/Helios - Eingya.jpg"),
   JAMES_BLAKE_JAMES_BLAKE("James Blake - James Blake", "src/main/resources/images/James Blake - James Blake.jpg"),
   JON_HOPKINS_IMMUNITY("Jon Hopkins - Immunity", "src/main/resources/images/Jon Hopkins - Immunity.jpg"),
   JUSTICE_CROSS("Justice - Cross", "src/main/resources/images/Justice - Cross.jpg"),
   KANYE_WEST_808S_HEARTBREAK("Kanye West - 808s & Heartbreak", "src/main/resources/images/Kanye West - 808s & Heartbreak.jpg"),
   KASHIWA_DAISUKE_PROGRAM_MUSIC("Kashiwa Daisuke - Program Music", "src/main/resources/images/Kashiwa Daisuke - Program Music.jpg"),
   KLAUS_SCHULZE_TIMEWIND("Klaus Schulze - Timewind", "src/main/resources/images/Klaus Schulze - Timewind.jpg"),
   LONE_GALAXY_GARDEN("Lone - Galaxy Garden", "src/main/resources/images/Lone - Galaxy Garden.jpg"),
   MACHINEDRUM_ROOM("Machinedrum - Room(s)", "src/main/resources/images/Machinedrum - Room(s).jpg"),
   MANUEL_GOTTSCHING_E2_E4("Manuel Gottsching - e2 - e4", "src/main/resources/images/Manuel Gottsching - e2 - e4.jpg"),
   MASSIVE_ATTACK_MEZZANINE("Massive Attack - Mezzanine", "src/main/resources/images/Massive Attack - Mezzanine.jpg"),
   MORT_GARRISON_PLANTASIA("Mort Garrison - Plantasia", "src/main/resources/images/Mort Garrison - Plantasia.jpg"),
   NEU_NEU("Neu! - Neu!", "src/main/resources/images/Neu! - Neu!.jpg"),
   NICOLAS_JAAR_SPACE_IS_ONLY_NOISE("Nicolas Jaar - Space Is Only Noise", "src/main/resources/images/Nicolas Jaar - Space Is Only Noise.jpg"),
   NUJABES_METAPHORICAL_MUSIC("Nujabes - Metaphorical Music", "src/main/resources/images/Nujabes - Metaphorical Music.jpg"),
   ORB_THE_ORBS_ADVENTURES_BEYOND_THE_ULTRAWORLD("Orb - The Orbs Adventures Beyond The Ultraworld", "src/main/resources/images/Orb - The Orbs Adventures Beyond The Ultraworld.jpg"),
   ORBITAL_BROWN_ALBUM("Orbital - Brown Album", "src/main/resources/images/Orbital - Brown Album.jpg"),
   RADIOHEAD_KID_A("Radiohead - Kid A", "src/main/resources/images/Radiohead - Kid A.jpg"),
   RADIOHEAD_OK_COMPUTER("Radiohead - OK Computer", "src/main/resources/images/Radiohead - OK Computer.jpg"),
   SASHA_JOHN_FIGWEED_NORTHEN_EXPOSURE("Sasha & John Figweed - Northen Exposure", "src/main/resources/images/Sasha & John Figweed - Northen Exposure.jpg"),
   SHPONGLE_ARE_YOU_SHPONGLED("Shpongle - Are You Shpongled", "src/main/resources/images/Shpongle - Are You Shpongled.jpg"),
   TOKIMONSTA_MIDNIGHT_MENU("TOKiMONSTA - Midnight Menu", "src/main/resources/images/TOKiMONSTA - Midnight Menu.jpg"),
   TANGERINE_DREAM_PHAEDRA("Tangerine Dream - Phaedra", "src/main/resources/images/Tangerine Dream - Phaedra.jpg"),
   THE_AVALANCHES_SINCE_I_LEFT_YOU("The Avalanches - Since I left You", "src/main/resources/images/The Avalanches - Since I left You.jpg"),
   THE_FUTURE_SOUND_OF_LONDON_LIFEFORMS("The Future Sound Of London - Lifeforms", "src/main/resources/images/The Future Sound Of London - Lifeforms.jpg"),
   THE_FUTURE_SOUND_OF_LONDON_ACCELERATOR("The Future Sound of London - Accelerator", "src/main/resources/images/The Future Sound of London - Accelerator.jpg"),
   THE_KNIFE_SILENT_SHOUT("The Knife - Silent Shout", "src/main/resources/images/The Knife - Silent Shout.jpg"),
   TYCHO_DIVE("Tycho - Dive", "src/main/resources/images/Tycho - Dive.jpg"),
   VENETIAN_SNARES_ROSSZ_CSILLAG_ALATT_SZULETETT("Venetian Snares - Rossz Csillag Alatt Szuletett", "src/main/resources/images/Venetian Snares - Rossz Csillag Alatt Szuletett.jpg"),
   VILLALOBOS_ALCACHOFA("Villalobos - Alcachofa", "src/main/resources/images/Villalobos - Alcachofa.jpg")
   ;

   fullName : String
   pathName : String
end

function ImageView loadImageView(String path) {
    FileInputStream input = new FileInputStream(path);
    Image image = new Image(input);
    return new ImageView(image);
}

function AlbumAnswer showAlbumAlertAndGetAnswer(Album album) {

    FileInputStream input = new FileInputStream(album.getPathName());
    Image image = new Image(input);
    ImageView imageView = new ImageView(image);

    Alert alert = new Alert(Alert.AlertType.NONE, "",
                            ButtonType.YES, ButtonType.NO);

    DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(400);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(album.getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);
    alert.showAndWait();

    AlbumAnswer albumAnswer = new AlbumAnswer();
    albumAnswer.setAlbum(album);
    albumAnswer.setAns(alert.getResult().getText());
    return albumAnswer;
}

function QuestionAnswer alertOneButtonAlertAndGetTheAnswer(AlbumAnswer albumAnswer, String firstPossisbleAnswer) {
    ButtonType firstButton = new ButtonType(firstPossisbleAnswer);

    Alert alert = new Alert(Alert.AlertType.NONE,"" , firstButton);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(400);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(albumAnswer.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);
    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    return answer;
}

function QuestionAnswer alertTwoButtonsAndGetTheAnswer(AlbumAnswer albumAnswer,
                                                        String firstPossisbleAnswer, String secondPossibleAnswer) {

    ButtonType firstButton = new ButtonType(firstPossisbleAnswer);
    ButtonType secondButton = new ButtonType(secondPossibleAnswer);

    Alert alert = new Alert(Alert.AlertType.NONE, "", firstButton, secondButton);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    
    DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(590);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(albumAnswer.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);

    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    return answer;
}

function QuestionAnswer alertThreeButtonsAndGetTheAnswer(AlbumAnswer albumAnswer,
                                                        String firstPossisbleAnswer, String secondPossibleAnswer,
                                                        String thirdPossibleAnswer) {

    ButtonType firstButton = new ButtonType(firstPossisbleAnswer);
    ButtonType secondButton = new ButtonType(secondPossibleAnswer);
    ButtonType thirdButton = new ButtonType(thirdPossibleAnswer);

    Alert alert = new Alert(Alert.AlertType.NONE, "", firstButton,
                            secondButton, thirdButton);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    
	DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(800);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(albumAnswer.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);

    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    return answer;
}

function QuestionAnswer alertFourButtonsAndGetTheAnswer(AlbumAnswer albumAnswer,
                                                        String firstPossisbleAnswer, String secondPossibleAnswer,
                                                        String thirdPossibleAnswer, String fourthPossibleAnswer) {

    ButtonType firstButton = new ButtonType(firstPossisbleAnswer);
    ButtonType secondButton = new ButtonType(secondPossibleAnswer);
    ButtonType thirdButton = new ButtonType(thirdPossibleAnswer);
    ButtonType fourthButton = new ButtonType(fourthPossibleAnswer);

    Alert alert = new Alert(Alert.AlertType.NONE, "", firstButton,
                            secondButton, thirdButton, fourthButton);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    
	DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(1000);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(albumAnswer.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);

    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    return answer;
}
