package com.drools.example

import java.io.FileInputStream

import org.kie.api.runtime.KieRuntime

import javafx.scene.control.Alert
import javafx.scene.control.ButtonType
import javafx.scene.image.Image
import javafx.scene.image.ImageView
import javafx.scene.control.DialogPane
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.StackPane
import javafx.scene.control.Label
import javafx.scene.layout.GridPane
import javafx.geometry.Pos
import javafx.scene.text.Font
import javafx.stage.Stage
import javafx.scene.control.Button
import javafx.scene.Scene


declare QuestionAnswer
    ans : String
    previousAlbum: Album
end


declare AlbumAnswer
    album : Album
    ans   : String
end


global Stage primaryStage

rule "Initial rule"
when

then
	AlbumAnswer albumAnswer = new AlbumAnswer();
	albumAnswer.setAlbum(Album.ELECTRONIC_MUSIC);
	QuestionAnswer questionAnswer = alertThreeButtonsAndGetTheAnswer(albumAnswer,
                                    "I like rock music", 
                                    "I like rap music",
                                    "Let\'s start with something electronic");

    insert( questionAnswer );
	
end

rule "Album Answer yes"
when
    a  : AlbumAnswer( ans.equals("Yes") )
then

	FileInputStream albumPath = new FileInputStream(a.getAlbum().getPathName());
    Image img = new Image(albumPath);
    ImageView imageV = new ImageView(img);
	
	
    Alert alerts = new Alert(Alert.AlertType.NONE, "", ButtonType.CLOSE );
	DialogPane dialogPane = alerts.getDialogPane();
    GridPane grid = new GridPane();
    
    Label topLabel = new Label("The album for you:");
    topLabel.setAlignment(Pos.CENTER);
    topLabel.setMaxWidth(Double.MAX_VALUE);
    topLabel.setMaxHeight(Double.MAX_VALUE);
    topLabel.setMinHeight(80.0);
    topLabel.setFont(new Font("Arial", 20));
    grid.add(topLabel, 0,0);
    
    StackPane stackPane = new StackPane(imageV);
    stackPane.setMinWidth(750);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,1);

    Label bottomLabel = new Label(a.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,2);

    dialogPane.setHeader(grid);
    alerts.showAndWait();
     
end

rule "I like rap music"
when
    questionAnswer : QuestionAnswer( ans.equals("I like rap music") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.KANYE_WEST_808S_HEARTBREAK);
    insert( albumAnswer );

end

rule "I like rock music"
when
    questionAnswer : QuestionAnswer( ans.equals("I like rock music") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.RADIOHEAD_OK_COMPUTER);
    insert( albumAnswer );

end

rule "Let\'s start with something electronic"
when
    questionAnswer : QuestionAnswer( ans.equals("Let\'s start with something electronic") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.DAFT_PUNK_DISCOVERY);
    insert( albumAnswer );

end

rule "Kanye West - 808 & Heartbreak answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.KANYE_WEST_808S_HEARTBREAK )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                    "Come on, I want REAL rap music", "Give me some nice hip-hop beats");

    insert( questionAnswer );

end

rule "Come On, I want REAL rap music"
when
    questionAnswer : QuestionAnswer( ans.equals("Come on, I want REAL rap music") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.GIRL_TALK_FEED_THE_ANIMALS);
    insert( albumAnswer );

end

rule "Give me some nice hip-hop beats"
when
    questionAnswer : QuestionAnswer( ans.equals("Give me some nice hip-hop beats") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.NUJABES_METAPHORICAL_MUSIC);
    insert( albumAnswer );

end

rule "Girl talk, feed the animals answer"
when
    albumAnswer: AlbumAnswer( ans.equals("No") && album == Album.GIRL_TALK_FEED_THE_ANIMALS)
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                        "Whoa, sampling is cool, more like that");
    insert( questionAnswer );

 end

rule "Whoa, sampling is cool, more like that"
when
    questionAnswer : QuestionAnswer( ans.equals("Whoa, sampling is cool, more like that") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.THE_AVALANCHES_SINCE_I_LEFT_YOU);
    insert( albumAnswer );

end

rule "DJ_SHADOW_ENDTRODUCING answer"
when
    albumAnswer: AlbumAnswer( ans.equals("No") && album == Album.DJ_SHADOW_ENDTRODUCING)
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                        "I'm liking these instrumental beats. More please");
    insert( questionAnswer );

 end

rule "I'm liking these instrumental beats. More please"
when
    questionAnswer : QuestionAnswer( ans.equals("I'm liking these instrumental beats. More please") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.NUJABES_METAPHORICAL_MUSIC);
    insert( albumAnswer );

end

rule "Avalanches - Since I Left You answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.THE_AVALANCHES_SINCE_I_LEFT_YOU )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                    "More sampling, with a hip-hop vibe to it", "Darker. Sadder. The samples could be messed with a little more.");

    insert( questionAnswer );

end

rule "More sampling, with a hip-hop vibe to it"
when
    questionAnswer : QuestionAnswer( ans.equals("More sampling, with a hip-hop vibe to it") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.DJ_SHADOW_ENDTRODUCING);
    insert( albumAnswer );

end

rule "Darker. Sadder. The samples could be messed with a little more."
when
    questionAnswer : QuestionAnswer( ans.equals("Darker. Sadder. The samples could be messed with a little more.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.BURIAL_UNTRUE);
    insert( albumAnswer );

end

rule "Keep the beats, but make it dark and operatic."
when
    questionAnswer : QuestionAnswer( ans.equals("Keep the beats, but make it dark and operatic.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.BURIAL_UNTRUE);
    insert( albumAnswer );

end

rule "Burial - Untrue"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.BURIAL_UNTRUE )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                    "Happier, Lighter, Focus on the beats, not the vocals",
                                    "Drop the samples, keep the nice beats and dark amosphere.");

    insert( questionAnswer );

end

rule "Happier, Lighter, Focus on the beats, not the vocals"
when
    questionAnswer : QuestionAnswer( ans.equals("Happier, Lighter, Focus on the beats, not the vocals") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.TOKIMONSTA_MIDNIGHT_MENU);
    insert( albumAnswer );

end

rule "Drop the samples, keep the nice beats and dark amosphere."
when
    questionAnswer : QuestionAnswer( ans.equals("Drop the samples, keep the nice beats and dark amosphere.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.MASSIVE_ATTACK_MEZZANINE);
    insert( albumAnswer );

end

rule "Massive Attack - Mezzanine"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.MASSIVE_ATTACK_MEZZANINE )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                    "I liked the feel of Burial a little better.");

    insert( questionAnswer );

end

rule "I liked the feel of Burial a little better."
when
    questionAnswer : QuestionAnswer( ans.equals("I liked the feel of Burial a little better.") )
then

	AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.JAMES_BLAKE_JAMES_BLAKE);
    insert(answer);

end

rule "NUJABES_METAPHORICAL_MUSIC answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.NUJABES_METAPHORICAL_MUSIC )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                    "I need more of these lush, organic sounds",
                                    "Stranger! Wonkier!");
    questionAnswer.setPreviousAlbum(albumAnswer.getAlbum());
    insert( questionAnswer );

end

rule "Stranger! Wonkier!"
when
    questionAnswer : QuestionAnswer( ans.equals("Stranger! Wonkier!") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.TOKIMONSTA_MIDNIGHT_MENU);
    insert( albumAnswer );

end

rule "TOKIMONSTA_MIDNIGHT_MENU answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.TOKIMONSTA_MIDNIGHT_MENU )
then

    QuestionAnswer questionAnswer = alertFourButtonsAndGetTheAnswer(albumAnswer,
                                   "I like those beats. What if they were a bit more spaced out?",
                                   "I can deal with the weird parts. I think I'm ready for the classics",
                                   "Even stranger! Even wonkier!",
                                   "Keep the beats, but make it dark and operatic.");

    insert( questionAnswer );

end

rule "Even stranger! Even wonkier!"
when
    questionAnswer : QuestionAnswer( ans.equals("Even stranger! Even wonkier!") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.FLYING_LOTUS_COSMOGRAMMA);
    insert( albumAnswer );

end

rule "That sounds dated. Something more recent?"
when
    questionAnswer : QuestionAnswer( ans.equals("That sounds dated. Something more recent?") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.FLYING_LOTUS_COSMOGRAMMA);
    insert( albumAnswer );

end

rule "FLYING_LOTUS_COSMOGRAMMA answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.FLYING_LOTUS_COSMOGRAMMA )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "I want this, but in a jungle");

    insert( questionAnswer );

end

rule "I want this, but in a jungle"
when
    questionAnswer : QuestionAnswer( ans.equals("I want this, but in a jungle") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.LONE_GALAXY_GARDEN);
    insert( albumAnswer );

end

rule "LONE_GALAXY_GARDEN answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.LONE_GALAXY_GARDEN )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                   "Rainforest music, but slightly less crazy",
                                   "I loved the strange vocals that a few of the trachs had. And the drums.");

    insert( questionAnswer );

end

rule "MACHINEDRUM_ROOM answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.MACHINEDRUM_ROOM )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "Those drums. 10 times louder. 10 times crazier.");

    insert( questionAnswer );

end

rule "Those drums. 10 times louder. 10 times crazier."
when
    questionAnswer : QuestionAnswer( ans.equals("Those drums. 10 times louder. 10 times crazier.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.VENETIAN_SNARES_ROSSZ_CSILLAG_ALATT_SZULETETT);
    insert( albumAnswer );

end

rule "VENETIAN_SNARES_ROSSZ_CSILLAG_ALATT_SZULETETT answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.VENETIAN_SNARES_ROSSZ_CSILLAG_ALATT_SZULETETT )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "Calm down those drums. I like the orchestral samples though.");

    insert( questionAnswer );

end

rule "Calm down those drums. I like the orchestral samples though."
when
    questionAnswer : QuestionAnswer( ans.equals("Calm down those drums. I like the orchestral samples though.") )
then

    AlbumAnswer answer = new AlbumAnswer();
        answer.setAns("Yes");
        answer.setAlbum(Album.KASHIWA_DAISUKE_PROGRAM_MUSIC);
        insert(answer);

end

rule "I loved the strange vocals that a few of the trachs had. And the drums."
when
    questionAnswer : QuestionAnswer( ans.equals("I loved the strange vocals that a few of the trachs had. And the drums.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.MACHINEDRUM_ROOM);
    insert( albumAnswer );

end

rule "Rainforest music, but slightly less crazy"
when
    questionAnswer : QuestionAnswer( ans.equals("Rainforest music, but slightly less crazy") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.THE_FUTURE_SOUND_OF_LONDON_LIFEFORMS);
    insert( albumAnswer );

end

rule "More!"
when
    questionAnswer : QuestionAnswer( ans.equals("More!") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.THE_FUTURE_SOUND_OF_LONDON_LIFEFORMS);
    insert( albumAnswer );

end

rule "Less melody, more subtle"
when
    questionAnswer : QuestionAnswer( ans.equals("Less melody, more subtle") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.VILLALOBOS_ALCACHOFA);
    insert(answer);

end

rule "This is much to busy and melodious for my tastes"
when
    questionAnswer : QuestionAnswer( ans.equals("This is much to busy and melodious for my tastes") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.VILLALOBOS_ALCACHOFA);
    insert(answer);

end

rule "I need more of these lush, organic sounds - when from Bonobo - Black Sand"
when
    questionAnswer : QuestionAnswer( ans.equals("I need more of these lush, organic sounds"),
                                     previousAlbum == Album.BONOBO_BLACK_SANDS)
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.NUJABES_METAPHORICAL_MUSIC);
    insert( albumAnswer );

end

rule "I need more of these lush, organic sounds - when from Nujabes - Metaphorical Music"
when
    questionAnswer : QuestionAnswer( ans.equals("I need more of these lush, organic sounds") &&
                                     previousAlbum == Album.NUJABES_METAPHORICAL_MUSIC )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.BONOBO_BLACK_SANDS);
    insert( albumAnswer );

end

rule "Chill it out"
when
    questionAnswer : QuestionAnswer( ans.equals("Chill it out") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.TYCHO_DIVE);
    insert( albumAnswer );

end

rule "Where can I go from here?"
when
    questionAnswer : QuestionAnswer( ans.equals("Where can I go from here?") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.BONOBO_BLACK_SANDS);
    insert( albumAnswer );

end

rule "BONOBO_BLACK_SANDS answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.BONOBO_BLACK_SANDS )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                   "I need more of these lush, organic sounds",
                                   "Chill it out");
    questionAnswer.setPreviousAlbum(albumAnswer.getAlbum());
    insert( questionAnswer );

end

rule "THE_FUTURE_SOUND_OF_LONDON_LIFEFORMS answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.THE_FUTURE_SOUND_OF_LONDON_LIFEFORMS )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "I think I'm ready for some ambient now.");

    insert( questionAnswer );

end

rule "I think I'm ready for some ambient now."
when
    questionAnswer : QuestionAnswer( ans.equals("I think I'm ready for some ambient now.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.GLOBAL_COMMUNICATION_76_14);
    insert( albumAnswer );

end

rule "Make it stranger. I want to listen to an educational film from the eighties"
when
    questionAnswer : QuestionAnswer( ans.equals("Make it stranger. I want to listen to an educational film from the eighties") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.BOARDS_OF_CANADA_MUSIC_HAS_THE_RIGHT_TO_CHILDREN);
    insert( albumAnswer );

end

rule "TYCHO_DIVE answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.TYCHO_DIVE )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "Make it stranger. I want to listen to an educational film from the eighties"
                                   );

    insert( questionAnswer );

end

rule "BOARDS_OF_CANADA_MUSIC_HAS_THE_RIGHT_TO_CHILDREN answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.BOARDS_OF_CANADA_MUSIC_HAS_THE_RIGHT_TO_CHILDREN )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "I want something more \"electric\" feeling"
                                   );

    insert( questionAnswer );

end

rule "I want something more \"electric\" feeling"
when
    questionAnswer : QuestionAnswer( ans.equals("I want something more \"electric\" feeling") )
then
    
    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.APHEX_TWIN_SELECTED_AMBIENT_WORKS);
    insert(answer);

end

rule "I like those beats. What if they were a bit more spaced out?"
when
    questionAnswer : QuestionAnswer( ans.equals("I like those beats. What if they were a bit more spaced out?") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.BOARDS_OF_CANADA_MUSIC_HAS_THE_RIGHT_TO_CHILDREN);
    insert( albumAnswer );

end

rule "I can deal with the weird parts. I think I'm ready for the classics"
when
    questionAnswer : QuestionAnswer( ans.equals("I can deal with the weird parts. I think I'm ready for the classics") )
then
    
    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.APHEX_TWIN_SELECTED_AMBIENT_WORKS);
    insert(answer);

end

rule "Cool, I guess electronic music isn\'t just talentless button pushing. More like this"
when
    questionAnswer : QuestionAnswer( ans.equals("Cool, I guess electronic music isn\'t just talentless button pushing. More like this") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.APHEX_TWIN_DRUKQS);
    insert( albumAnswer );

end

rule "APHEX_TWIN_DRUKQS answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.APHEX_TWIN_DRUKQS )
then

    QuestionAnswer questionAnswer = alertFourButtonsAndGetTheAnswer(albumAnswer,
                                   "I can\'t wrap my head around these drums, but I like the rest of it. No drums",
                                   "That sounds dated. Something more recent?",
                                   "Let\'s get a steady beat on that",
                                   "These complex beats are awesome. Can they get wilder?");

    insert( questionAnswer );

end

rule "I can\'t wrap my head around these drums, but I like the rest of it. No drums"
when
    questionAnswer : QuestionAnswer( ans.equals("I can\'t wrap my head around these drums, but I like the rest of it. No drums") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.KLAUS_SCHULZE_TIMEWIND);
    insert( albumAnswer );

end

rule "These complex beats are awesome. Can they get wilder?"
when
    questionAnswer : QuestionAnswer( ans.equals("These complex beats are awesome. Can they get wilder?") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.MACHINEDRUM_ROOM);
    insert( albumAnswer );

end

rule "More drums"
when
    questionAnswer : QuestionAnswer( ans.equals("More drums") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.AUTECHRE_AMBER);
    insert( albumAnswer );

end

rule "I like the glitchy drums"
when
    questionAnswer : QuestionAnswer( ans.equals("I like the glitchy drums") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.AUTECHRE_AMBER);
    insert( albumAnswer );

end

rule "I actually liked the drums and bleeps they had going on. More of that - AUTECHRE"
when
    questionAnswer : QuestionAnswer( ans.equals("I actually liked the drums and bleeps they had going on. More of that") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.AUTECHRE_AMBER);
    questionAnswer.setAns("");
    update(questionAnswer);
    insert( albumAnswer );

end

rule "I actually liked the drums and bleeps they had going on. More of that - APHEX"
when
    questionAnswer : QuestionAnswer( ans.equals("I actually liked the drums and bleeps they had going on. More of that") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.APHEX_TWIN_SELECTED_AMBIENT_WORKS);
    questionAnswer.setAns("");
    update(questionAnswer);
    insert( albumAnswer );

end

rule "AUTECHRE_AMBER answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.AUTECHRE_AMBER )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "Cool, I guess electronic music isn\'t just talentless button pushing. More like this"
                                   );

    insert( questionAnswer );

end

rule "KLAUS_SCHULZE_TIMEWIND answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.KLAUS_SCHULZE_TIMEWIND )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                   "Let\'s get a steady beat on that",
                                   "More drums");

    insert( questionAnswer );

end

rule "Let\'s get a steady beat on that"
when
    questionAnswer : QuestionAnswer( ans.equals("Let\'s get a steady beat on that") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.ORB_THE_ORBS_ADVENTURES_BEYOND_THE_ULTRAWORLD);
    insert( albumAnswer );

end

rule "ORB_THE_ORBS_ADVENTURES_BEYOND_THE_ULTRAWORLD answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.ORB_THE_ORBS_ADVENTURES_BEYOND_THE_ULTRAWORLD )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "Something a little bit less ambient maybe");
    insert( questionAnswer );
end

rule "Something a little bit less ambient maybe"
when
    questionAnswer : QuestionAnswer( ans.equals("Something a little bit less ambient maybe") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.THE_FUTURE_SOUND_OF_LONDON_ACCELERATOR);
    insert( albumAnswer );

end

rule "THE_FUTURE_SOUND_OF_LONDON_ACCELERATOR answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.THE_FUTURE_SOUND_OF_LONDON_ACCELERATOR )
then

    QuestionAnswer questionAnswer = alertThreeButtonsAndGetTheAnswer(albumAnswer,
                                   "More",
                                   "I want to feel like I'm on drugs.",
                                   "focus on fast, hard hitting drums.");

    insert( questionAnswer );

end

rule "GLOBAL_COMMUNICATION_76_14 answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.GLOBAL_COMMUNICATION_76_14 )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "Even more ambient");

    insert( questionAnswer );

end

rule "focus on fast, hard hitting drums."
when
    questionAnswer : QuestionAnswer( ans.equals("focus on fast, hard hitting drums.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.GOLDIE_TIMELESS);
    insert( albumAnswer );

end

rule "GOLDIE_TIMELESS answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.GOLDIE_TIMELESS )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "This, but I want to feel like I'm exploring a frozen wasteland.");
    insert( questionAnswer );
end

rule "Even more ambient"
when
    questionAnswer : QuestionAnswer( ans.equals("Even more ambient") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.BRIAN_ENO_AMBIENT_2_PLATEAUX_OF_MIRROR);
    insert( albumAnswer );

end

rule "BRIAN_ENO_AMBIENT_2_PLATEAUX_OF_MIRROR answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.BRIAN_ENO_AMBIENT_2_PLATEAUX_OF_MIRROR )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                   "This album is too busy for me.",
                                   "Mix the two.");
    insert( questionAnswer );
end

rule "SHPONGLE_ARE_YOU_SHPONGLED answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.SHPONGLE_ARE_YOU_SHPONGLED )
then

    QuestionAnswer questionAnswer = alertThreeButtonsAndGetTheAnswer(albumAnswer,
                                   "focus on fast, hard hitting drums.",
                                   "I like this careless, fun music I can kind of dance to. Give me a big, essential, diverse collection of it.",
                                   "This, but I want to feel like I'm exploring a frozen wasteland.");
    insert( questionAnswer );
end

rule "Mix the two."
when
    questionAnswer : QuestionAnswer( ans.equals("Mix the two.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.JON_HOPKINS_IMMUNITY);
    insert( albumAnswer );

end

rule "JON_HOPKINS_IMMUNITY answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.JON_HOPKINS_IMMUNITY )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                   "I liked the piano, but not the heavy parts",
                                   "I liked the heavier bits, Collider for example.");
    insert( questionAnswer );
end



rule "DAFT_PUNK_DISCOVERY answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.DAFT_PUNK_DISCOVERY )
then

    QuestionAnswer questionAnswer = alertFourButtonsAndGetTheAnswer(albumAnswer,
                                   "I don't ever want to stop dancing.",
                                   "DIRTIER",
                                   "I like this careless, fun music I can kind of dance to. Give me a big, essential, diverse collection of it.",
                                   "Fun stuff, but could it get a little more... Tribal?");
    questionAnswer.setPreviousAlbum(albumAnswer.getAlbum());
    insert( questionAnswer );
end

rule "DIRTIER"
when
    questionAnswer : QuestionAnswer( ans.equals("DIRTIER") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.JUSTICE_CROSS);
    insert(answer);

end

rule "I don't ever want to stop dancing - when from Daft Punk - Discovery"
when
    questionAnswer : QuestionAnswer( ans.equals("I don't ever want to stop dancing."),
                                     previousAlbum == Album.DAFT_PUNK_DISCOVERY)
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.ORBITAL_BROWN_ALBUM);
    insert( albumAnswer );

end

rule "ORBITAL_BROWN_ALBUM answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.ORBITAL_BROWN_ALBUM )
then

    QuestionAnswer questionAnswer = alertFourButtonsAndGetTheAnswer(albumAnswer,
                                   "I don't ever want to stop dancing.",
                                   "Mix the two.",
                                   "Less melody, more subtle",
                                   "I liked Halcyon + On + ON");
    questionAnswer.setPreviousAlbum(albumAnswer.getAlbum());
    insert( questionAnswer );

end

rule "I liked Halcyon + On + ON"
when
    questionAnswer : QuestionAnswer( ans.equals("I liked Halcyon + On + ON") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.GLOBAL_COMMUNICATION_76_14);
    insert( albumAnswer );

end

rule "I don't ever want to stop dancing. - when from Orbital - Brown Album"
when
    questionAnswer : QuestionAnswer( ans.equals("I don't ever want to stop dancing."),
                                     previousAlbum == Album.ORBITAL_BROWN_ALBUM)
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.DAFT_PUNK_DISCOVERY);
    insert( albumAnswer );

end

rule "Fun stuff, but could it get a little more... Tribal?"
when
    questionAnswer : QuestionAnswer( ans.equals("Fun stuff, but could it get a little more... Tribal?") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.SHPONGLE_ARE_YOU_SHPONGLED);
    insert( albumAnswer );

end


rule "I want to feel like I'm on drugs."
when
    questionAnswer : QuestionAnswer( ans.equals("I want to feel like I'm on drugs.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.SHPONGLE_ARE_YOU_SHPONGLED);
    insert( albumAnswer );

end

rule "I like this careless, fun music I can kind of dance to. Give me a big, essential, diverse collection of it."
when
    questionAnswer : QuestionAnswer( ans.equals("I like this careless, fun music I can kind of dance to. Give me a big, essential, diverse collection of it.") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.SASHA_JOHN_FIGWEED_NORTHEN_EXPOSURE);
    insert(answer);

end

rule "This, but I want to feel like I'm exploring a frozen wasteland."
when
    questionAnswer : QuestionAnswer( ans.equals("This, but I want to feel like I'm exploring a frozen wasteland.") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.SASHA_JOHN_FIGWEED_NORTHEN_EXPOSURE);
    insert(answer);

end

rule "I liked the heavier bits, Collider for example."
when
    questionAnswer : QuestionAnswer( ans.equals("I liked the heavier bits, Collider for example.") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.DAFT_PUNK_DISCOVERY);
    insert( albumAnswer );

end

rule "I liked the piano, but not the heavy parts"
when
    questionAnswer : QuestionAnswer( ans.equals("I liked the piano, but not the heavy parts") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.HELIOS_EINGYA);
    insert(answer);

end

rule "This album is too busy for me."
when
    questionAnswer : QuestionAnswer( ans.equals("This album is too busy for me.") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.BRIAN_ENO_AMBIENT_1_MUSIC_FOR_AIRPORTS);
    insert(answer);

end

rule "KASHIWA_DAISUKE_PROGRAM_MUSIC answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.KASHIWA_DAISUKE_PROGRAM_MUSIC )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                   "I like the glitchy drums",
                                   "I like the more ambient parts");

    insert( questionAnswer );

end

rule "I like the more ambient parts"
when
    questionAnswer : QuestionAnswer( ans.equals("I like the more ambient parts") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.TANGERINE_DREAM_PHAEDRA);
    insert( albumAnswer );

end

rule "NEU_NEU answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.NEU_NEU )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                   "More electronic influence",
                                   "This, but electronic");

    insert( questionAnswer );

end

rule "More electronic influence"
when
    questionAnswer : QuestionAnswer( ans.equals("More electronic influence") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.MANUEL_GOTTSCHING_E2_E4);
    insert( albumAnswer );

end

rule "This, but electronic"
when
    questionAnswer : QuestionAnswer( ans.equals("This, but electronic") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.KLAUS_SCHULZE_TIMEWIND);
    insert( albumAnswer );

end

rule "MANUEL_GOTTSCHING_E2_E4 answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.MANUEL_GOTTSCHING_E2_E4 )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "Fully electronic now");

    insert( questionAnswer );

end

rule "Fully electronic now"
when
    questionAnswer : QuestionAnswer( ans.equals("Fully electronic now") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.TANGERINE_DREAM_PHAEDRA);
    insert( albumAnswer );

end

rule "TANGERINE_DREAM_PHAEDRA answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.TANGERINE_DREAM_PHAEDRA )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
                                   "More ambient stuff",
                                   "This style of syths, but shorter songs and carelessly happy");

    insert( questionAnswer );

end

rule "More ambient stuff"
when
    questionAnswer : QuestionAnswer( ans.equals("More ambient stuff") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.GLOBAL_COMMUNICATION_76_14);
    insert( albumAnswer );

end

rule "This style of syths, but shorter songs and carelessly happy"
when
    questionAnswer : QuestionAnswer( ans.equals("This style of syths, but shorter songs and carelessly happy") )
then
	
	AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.MORT_GARRISON_PLANTASIA);
    insert(answer);
	
end

rule "FUCK_BUTTONS_TAROT_SPORT answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.FUCK_BUTTONS_TAROT_SPORT )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "More, quieter though");

    insert( questionAnswer );

end

rule "More, quieter though"
when
    questionAnswer : QuestionAnswer( ans.equals("More, quieter though") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.TANGERINE_DREAM_PHAEDRA);
    insert( albumAnswer );

end

rule "GODSPEED_YOU_BLACK_EMPEROR_LIFT_YOUR_SKINNY_FISTS_LIKE_ANTENNAS_TO_HEAVEN answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.GODSPEED_YOU_BLACK_EMPEROR_LIFT_YOUR_SKINNY_FISTS_LIKE_ANTENNAS_TO_HEAVEN )
then

    QuestionAnswer questionAnswer = alertThreeButtonsAndGetTheAnswer(albumAnswer,
                                   "I love those buildups! I could try some electronic music that does that",
                                   "I think I could handle that, but way more minimal",
                                   "I like the post-rock structure and scale");

    insert( questionAnswer );

end

rule "I love those buildups! I could try some electronic music that does that"
when
    questionAnswer : QuestionAnswer( ans.equals("I love those buildups! I could try some electronic music that does that") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.FUCK_BUTTONS_TAROT_SPORT);
    insert( albumAnswer );

end

rule "I think I could handle that, but way more minimal"
when
    questionAnswer : QuestionAnswer( ans.equals("I think I could handle that, but way more minimal") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.NEU_NEU);
    insert( albumAnswer );

end

rule "I like the post-rock structure and scale"
when
    questionAnswer : QuestionAnswer( ans.equals("I like the post-rock structure and scale") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.KASHIWA_DAISUKE_PROGRAM_MUSIC);
    insert( albumAnswer );

end

rule "RADIOHEAD_KID_A answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.RADIOHEAD_KID_A )
then

    QuestionAnswer questionAnswer = alertFourButtonsAndGetTheAnswer(albumAnswer,
                                   "I actually liked the drums and bleeps they had going on. More of that",
                                   "Even this is too much electronic for me",
                                   "Cool, but I\'m not quite ready to lose the guitars quite yet",
                                   "Weird, but good! Maybe more electronic, but I still want vocals");

    insert( questionAnswer );

end

rule  "Cool, but I\'m not quite ready to lose the guitars quite yet"
when
    questionAnswer : QuestionAnswer( ans.equals( "Cool, but I\'m not quite ready to lose the guitars quite yet") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.DARKSIDE_PSYCHIC);
    insert( albumAnswer );

end

rule  "Weird, but good! Maybe more electronic, but I still want vocals"
when
    questionAnswer : QuestionAnswer( ans.equals( "Weird, but good! Maybe more electronic, but I still want vocals") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.THE_KNIFE_SILENT_SHOUT);
    insert( albumAnswer );

end


rule "Even this is too much electronic for me"
when
    questionAnswer : QuestionAnswer( ans.equals("Even this is too much electronic for me") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.GODSPEED_YOU_BLACK_EMPEROR_LIFT_YOUR_SKINNY_FISTS_LIKE_ANTENNAS_TO_HEAVEN);
    insert( albumAnswer );

end

rule "RADIOHEAD_OK_COMPUTER answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.RADIOHEAD_OK_COMPUTER )
then

    QuestionAnswer questionAnswer = alertOneButtonAlertAndGetTheAnswer(albumAnswer,
                                   "Cool, but that\'s basically just rock music");

    insert( questionAnswer );

end

rule "Cool, but that\'s basically just rock music"
when
    questionAnswer : QuestionAnswer( ans.equals("Cool, but that\'s basically just rock music") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.RADIOHEAD_KID_A);
    insert( albumAnswer );

end

rule "Too weird!"
when
    questionAnswer : QuestionAnswer( ans.equals("Too weird!") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.DARKSIDE_PSYCHIC);
    insert( albumAnswer );

end

rule "Take out the vocals. Focus it"
when
    questionAnswer : QuestionAnswer( ans.equals("Take out the vocals. Focus it") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.TOKIMONSTA_MIDNIGHT_MENU);
    insert( albumAnswer );

end

rule "THE_KNIFE_SILENT_SHOUT answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.THE_KNIFE_SILENT_SHOUT )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
    								"Take out the vocals. Focus it",
    								 "Too weird!");

    insert( questionAnswer );

end


rule "DARKSIDE_PSYCHIC answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.DARKSIDE_PSYCHIC )
then

    QuestionAnswer questionAnswer = alertThreeButtonsAndGetTheAnswer(albumAnswer,
    								"I like this. We can lose the guitars and stuff now. I\'m ready",
    								"More of the same, but I think I\'m ready for electronic music now",
    								"Where can I go from here?");

    insert( questionAnswer );

end

rule "More of the same, but I think I\'m ready for electronic music now"
when
    questionAnswer : QuestionAnswer( ans.equals("More of the same, but I think I\'m ready for electronic music now") )
then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.NICOLAS_JAAR_SPACE_IS_ONLY_NOISE);
    insert( albumAnswer );

end

rule "I like this. We can lose the guitars and stuff now. I\'m ready"
when
    questionAnswer : QuestionAnswer( ans.equals("I like this. We can lose the guitars and stuff now. I\'m ready") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.JAMES_BLAKE_JAMES_BLAKE);
    insert(answer);

end

rule "More of a vocal focus"
when
    questionAnswer : QuestionAnswer( ans.equals("More of a vocal focus") )
then

    AlbumAnswer answer = new AlbumAnswer();
    answer.setAns("Yes");
    answer.setAlbum(Album.JAMES_BLAKE_JAMES_BLAKE);
    insert(answer);

end

rule "NICOLAS_JAAR_SPACE_IS_ONLY_NOISE answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.NICOLAS_JAAR_SPACE_IS_ONLY_NOISE )
then

    QuestionAnswer questionAnswer = alertTwoButtonsAndGetTheAnswer(albumAnswer,
    								"More of a vocal focus",
    								"This is much to busy and melodious for my tastes");

    insert( questionAnswer );

end

declare enum Album
   ELECTRONIC_MUSIC("Electronic Music","src/main/resources/images/Electronic Music.jpg"),
   APHEX_TWIN_DRUKQS("Aphex Twin - Drukqs", "src/main/resources/images/Aphex Twin - Drukqs.jpg"),
   APHEX_TWIN_SELECTED_AMBIENT_WORKS("Aphex Twin - Selected Ambient Works", "src/main/resources/images/Aphex Twin - Selected Ambient Works.jpg"),
   AUTECHRE_AMBER("Autechre - Amber", "src/main/resources/images/Autechre - Amber.jpg"),
   BOARDS_OF_CANADA_MUSIC_HAS_THE_RIGHT_TO_CHILDREN("Boards of Canada - Music Has the Right to Children", "src/main/resources/images/Boards of Canada - Music Has the Right to Children.jpg"),
   BONOBO_BLACK_SANDS("Bonobo - Black Sands", "src/main/resources/images/Bonobo - Black Sands.jpg"),
   BRIAN_ENO_AMBIENT_1_MUSIC_FOR_AIRPORTS("Brian Eno - Ambient 1 Music For Airports", "src/main/resources/images/Brian Eno - Ambient 1 Music For Airports.jpg"),
   BRIAN_ENO_AMBIENT_2_PLATEAUX_OF_MIRROR("Brian Eno - Ambient 2 Plateaux Of Mirror", "src/main/resources/images/Brian Eno - Ambient 2 Plateaux Of Mirror.jpg"),
   BURIAL_UNTRUE("Burial - Untrue", "src/main/resources/images/Burial - Untrue.jpg"),
   DJ_SHADOW_ENDTRODUCING("DJ Shadow - Endtroducing", "src/main/resources/images/DJ Shadow - Endtroducing......jpg"),
   DAFT_PUNK_DISCOVERY("Daft Punk - Discovery", "src/main/resources/images/Daft Punk - Discovery.jpg"),
   DARKSIDE_PSYCHIC("Darkside - Psychic", "src/main/resources/images/Darkside - Psychic.jpg"),
   FLYING_LOTUS_COSMOGRAMMA("Flying Lotus - Cosmogramma", "src/main/resources/images/Flying Lotus - Cosmogramma.jpg"),
   FUCK_BUTTONS_TAROT_SPORT("Fuck Buttons - Tarot Sport", "src/main/resources/images/Fuck Buttons - Tarot Sport.jpg"),
   GIRL_TALK_FEED_THE_ANIMALS("Girl Talk - Feed The Animals", "src/main/resources/images/Girl Talk - Feed The Animals.jpg"),
   GLOBAL_COMMUNICATION_76_14("Global Communication - 76 14", "src/main/resources/images/Global Communication - 76 14.jpg"),
   GODSPEED_YOU_BLACK_EMPEROR_LIFT_YOUR_SKINNY_FISTS_LIKE_ANTENNAS_TO_HEAVEN("Godspeed You! Black Emperor - Lift Your Skinny Fists Like Antennas to Heaven", "src/main/resources/images/Godspeed You! Black Emperor - Lift Your Skinny Fists Like Antennas to Heaven.jpg"),
   GOLDIE_TIMELESS("Goldie - Timeless", "src/main/resources/images/Goldie - Timeless.jpg"),
   HELIOS_EINGYA("Helios - Eingya", "src/main/resources/images/Helios - Eingya.jpg"),
   JAMES_BLAKE_JAMES_BLAKE("James Blake - James Blake", "src/main/resources/images/James Blake - James Blake.jpg"),
   JON_HOPKINS_IMMUNITY("Jon Hopkins - Immunity", "src/main/resources/images/Jon Hopkins - Immunity.jpg"),
   JUSTICE_CROSS("Justice - Cross", "src/main/resources/images/Justice - Cross.jpg"),
   KANYE_WEST_808S_HEARTBREAK("Kanye West - 808s & Heartbreak", "src/main/resources/images/Kanye West - 808s & Heartbreak.jpg"),
   KASHIWA_DAISUKE_PROGRAM_MUSIC("Kashiwa Daisuke - Program Music", "src/main/resources/images/Kashiwa Daisuke - Program Music.jpg"),
   KLAUS_SCHULZE_TIMEWIND("Klaus Schulze - Timewind", "src/main/resources/images/Klaus Schulze - Timewind.jpg"),
   LONE_GALAXY_GARDEN("Lone - Galaxy Garden", "src/main/resources/images/Lone - Galaxy Garden.jpg"),
   MACHINEDRUM_ROOM("Machinedrum - Room(s)", "src/main/resources/images/Machinedrum - Room(s).jpg"),
   MANUEL_GOTTSCHING_E2_E4("Manuel Gottsching - e2 - e4", "src/main/resources/images/Manuel Gottsching - e2 - e4.jpg"),
   MASSIVE_ATTACK_MEZZANINE("Massive Attack - Mezzanine", "src/main/resources/images/Massive Attack - Mezzanine.jpg"),
   MORT_GARRISON_PLANTASIA("Mort Garrison - Plantasia", "src/main/resources/images/Mort Garrison - Plantasia.jpg"),
   NEU_NEU("Neu! - Neu!", "src/main/resources/images/Neu! - Neu!.jpg"),
   NICOLAS_JAAR_SPACE_IS_ONLY_NOISE("Nicolas Jaar - Space Is Only Noise", "src/main/resources/images/Nicolas Jaar - Space Is Only Noise.jpg"),
   NUJABES_METAPHORICAL_MUSIC("Nujabes - Metaphorical Music", "src/main/resources/images/Nujabes - Metaphorical Music.jpg"),
   ORB_THE_ORBS_ADVENTURES_BEYOND_THE_ULTRAWORLD("Orb - The Orbs Adventures Beyond The Ultraworld", "src/main/resources/images/Orb - The Orbs Adventures Beyond The Ultraworld.jpg"),
   ORBITAL_BROWN_ALBUM("Orbital - Brown Album", "src/main/resources/images/Orbital - Brown Album.jpg"),
   RADIOHEAD_KID_A("Radiohead - Kid A", "src/main/resources/images/Radiohead - Kid A.jpg"),
   RADIOHEAD_OK_COMPUTER("Radiohead - OK Computer", "src/main/resources/images/Radiohead - OK Computer.jpg"),
   SASHA_JOHN_FIGWEED_NORTHEN_EXPOSURE("Sasha & John Figweed - Northen Exposure", "src/main/resources/images/Sasha & John Figweed - Northen Exposure.jpg"),
   SHPONGLE_ARE_YOU_SHPONGLED("Shpongle - Are You Shpongled", "src/main/resources/images/Shpongle - Are You Shpongled.jpg"),
   TOKIMONSTA_MIDNIGHT_MENU("TOKiMONSTA - Midnight Menu", "src/main/resources/images/TOKiMONSTA - Midnight Menu.jpg"),
   TANGERINE_DREAM_PHAEDRA("Tangerine Dream - Phaedra", "src/main/resources/images/Tangerine Dream - Phaedra.jpg"),
   THE_AVALANCHES_SINCE_I_LEFT_YOU("The Avalanches - Since I left You", "src/main/resources/images/The Avalanches - Since I left You.jpg"),
   THE_FUTURE_SOUND_OF_LONDON_LIFEFORMS("The Future Sound Of London - Lifeforms", "src/main/resources/images/The Future Sound Of London - Lifeforms.jpg"),
   THE_FUTURE_SOUND_OF_LONDON_ACCELERATOR("The Future Sound of London - Accelerator", "src/main/resources/images/The Future Sound of London - Accelerator.jpg"),
   THE_KNIFE_SILENT_SHOUT("The Knife - Silent Shout", "src/main/resources/images/The Knife - Silent Shout.jpg"),
   TYCHO_DIVE("Tycho - Dive", "src/main/resources/images/Tycho - Dive.jpg"),
   VENETIAN_SNARES_ROSSZ_CSILLAG_ALATT_SZULETETT("Venetian Snares - Rossz Csillag Alatt Szuletett", "src/main/resources/images/Venetian Snares - Rossz Csillag Alatt Szuletett.jpg"),
   VILLALOBOS_ALCACHOFA("Villalobos - Alcachofa", "src/main/resources/images/Villalobos - Alcachofa.jpg")
   ;

   fullName : String
   pathName : String
end

function ImageView loadImageView(String path) {
    FileInputStream input = new FileInputStream(path);
    Image image = new Image(input);
    return new ImageView(image);
}

function AlbumAnswer showAlbumAlertAndGetAnswer(Album album) {

    FileInputStream input = new FileInputStream(album.getPathName());
    Image image = new Image(input);
    ImageView imageView = new ImageView(image);

    Alert alert = new Alert(Alert.AlertType.NONE, "",
                            ButtonType.YES, ButtonType.NO);

    DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

	Label topLabel = new Label("Do you want to end on that album?");
    topLabel.setAlignment(Pos.CENTER);
    topLabel.setMaxWidth(Double.MAX_VALUE);
    topLabel.setMaxHeight(Double.MAX_VALUE);
    topLabel.setFont(new Font("Arial", 20));
    topLabel.setMinHeight(80.0);
    grid.add(topLabel, 0,0);

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(750);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,1);

    Label bottomLabel = new Label(album.getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,2);

    dialogPane.setHeader(grid);
    alert.showAndWait();

    AlbumAnswer albumAnswer = new AlbumAnswer();
    albumAnswer.setAlbum(album);
    albumAnswer.setAns(alert.getResult().getText());
    return albumAnswer;
}

function QuestionAnswer alertOneButtonAlertAndGetTheAnswer(AlbumAnswer albumAnswer, String firstPossisbleAnswer) {
    ButtonType firstButton = new ButtonType(firstPossisbleAnswer);

    Alert alert = new Alert(Alert.AlertType.NONE,"" , firstButton);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(750);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(albumAnswer.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);
    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    return answer;
}

function QuestionAnswer alertTwoButtonsAndGetTheAnswer(AlbumAnswer albumAnswer,
                                                        String firstPossisbleAnswer, String secondPossibleAnswer) {

    ButtonType firstButton = new ButtonType(firstPossisbleAnswer);
    ButtonType secondButton = new ButtonType(secondPossibleAnswer);

    Alert alert = new Alert(Alert.AlertType.NONE, "", firstButton, secondButton);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    
    DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(900);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(albumAnswer.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);

    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    return answer;
}

function QuestionAnswer alertThreeButtonsAndGetTheAnswer(AlbumAnswer albumAnswer,
                                                        String firstPossisbleAnswer, String secondPossibleAnswer,
                                                        String thirdPossibleAnswer) {

    ButtonType firstButton = new ButtonType(firstPossisbleAnswer);
    ButtonType secondButton = new ButtonType(secondPossibleAnswer);
    ButtonType thirdButton = new ButtonType(thirdPossibleAnswer);

    Alert alert = new Alert(Alert.AlertType.NONE, "", firstButton,
                            secondButton, thirdButton);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    
	DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(1600);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(albumAnswer.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);

    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    return answer;
}

function QuestionAnswer alertFourButtonsAndGetTheAnswer(AlbumAnswer albumAnswer,
                                                        String firstPossisbleAnswer, String secondPossibleAnswer,
                                                        String thirdPossibleAnswer, String fourthPossibleAnswer) {

    ButtonType firstButton = new ButtonType(firstPossisbleAnswer);
    ButtonType secondButton = new ButtonType(secondPossibleAnswer);
    ButtonType thirdButton = new ButtonType(thirdPossibleAnswer);
    ButtonType fourthButton = new ButtonType(fourthPossibleAnswer);

    Alert alert = new Alert(Alert.AlertType.NONE, "", firstButton,
                            secondButton, thirdButton, fourthButton);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    
	DialogPane dialogPane = alert.getDialogPane();
    GridPane grid = new GridPane();

    StackPane stackPane = new StackPane(imageView);
    stackPane.setMinWidth(1800);
    stackPane.setAlignment(Pos.CENTER);
    grid.add(stackPane, 0,0);

    Label bottomLabel = new Label(albumAnswer.getAlbum().getFullName());
    bottomLabel.setAlignment(Pos.CENTER);
    bottomLabel.setMaxWidth(Double.MAX_VALUE);
    bottomLabel.setMaxHeight(Double.MAX_VALUE);
    bottomLabel.setFont(new Font("Arial", 20));
    bottomLabel.setMinHeight(80.0);
    grid.add(bottomLabel, 0,1);

    dialogPane.setHeader(grid);

    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    return answer;
}
