package com.drools.example
import javafx.stage.Stage
import javafx.scene.control.Button
import javafx.scene.Scene
import java.io.FileInputStream
import javafx.scene.image.Image
import javafx.scene.image.ImageView
import org.kie.api.runtime.KieRuntime
import javafx.scene.control.Alert
import javafx.scene.control.ButtonType
import com.drools.example.AlbumAnswer
import javafx.scene.control.DialogPane


function ImageView loadImageView(String path) {
    FileInputStream input = new FileInputStream(path);
    Image image = new Image(input);
    return new ImageView(image);
}

function AlbumAnswer showAlbumAlertAndGetAnswer(Album album) {

    FileInputStream input = new FileInputStream(album.getPathName());
    Image image = new Image(input);
    ImageView imageView = new ImageView(image);

    Alert alert = new Alert(Alert.AlertType.NONE, album.getFullName(),
     ButtonType.YES, ButtonType.NO);
     alert.setGraphic(imageView);

     alert.showAndWait();

     AlbumAnswer albumAnswer = new AlbumAnswer();
     albumAnswer.setAlbum(album);
     albumAnswer.setAns(alert.getResult().getText());
     return albumAnswer;
}

declare QuestionAnswer
    ans : String
end

declare AlbumAnswer
    album : Album
    ans   : String
end


global Stage primaryStage

rule "Initial rule"
when

then

    AlbumAnswer albumAnswer = showAlbumAlertAndGetAnswer(Album.KANYE_WEST_808_AND_HEARTBREAK);
    insert( albumAnswer );

end

rule "Album Answer yes"
when
    a  : AlbumAnswer( ans.equals("Yes") )
then
    // metoda wykrywajaca koniec programu - na razie wyswietla puste okienko
    primaryStage.show();
end

rule "Kanye West - 808 & Heartbreak no answer"
when
    albumAnswer  : AlbumAnswer( ans.equals("No") && album == Album.KANYE_WEST_808_AND_HEARTBREAK )
then
    // utworz alert z jego odpowiedziami
    ButtonType realRapMusic = new ButtonType("Come on, I want REAL rap music");
    ButtonType giveMeSomeHipHopBeats = new ButtonType("Give me some nice hip-hop beats");



    Alert alert = new Alert(Alert.AlertType.NONE, albumAnswer.getAlbum().getFullName(),
             realRapMusic, giveMeSomeHipHopBeats);

    ImageView imageView = loadImageView(albumAnswer.getAlbum().getPathName());
    alert.setGraphic(imageView);

    alert.showAndWait();
    QuestionAnswer answer = new QuestionAnswer();
    answer.setAns(alert.getResult().getText());

    insert(answer);

end




declare enum Album
   KANYE_WEST_808_AND_HEARTBREAK("Kanye West - 808s & Heartbreak", "src/main/resources/images/Kanye West - 808s & Heartbreak.jpg");

   fullName : String
   pathName : String
end